spring.application.name=UserManagement_System_App



#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=Monish8384

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


# jwt auth ke liye ---> pHase 4 jwt auth   , secret key and time to expire 24 hours
jwt.secret=your-secret-key-your-secret-key-your-secret-key
jwt.expiration=86400000